// automatically generated by the FlatBuffers compiler, do not modify

package forfun.sandbox.uwns.shared.pack.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Actor extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Actor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int uid() { return bb.getInt(bb_pos + 0); }
  public boolean active() { return 0!=bb.get(bb_pos + 4); }
  public Vector position() { return position(new Vector()); }
  public Vector position(Vector obj) { return obj.__assign(bb_pos + 8, bb); }

  public static int createActor(FlatBufferBuilder builder, int uid, boolean active, float position_x, float position_y) {
    builder.prep(4, 16);
    builder.prep(4, 8);
    builder.putFloat(position_y);
    builder.putFloat(position_x);
    builder.pad(3);
    builder.putBoolean(active);
    builder.putInt(uid);
    return builder.offset();
  }
}

