// automatically generated by the FlatBuffers compiler, do not modify

package forfun.sandbox.uwns.shared.pack.flat;

public final class Message {
  private Message() { }
  public static final byte NONE = 0;
  public static final byte EnterWorldResponse = 1;
  public static final byte TargetPositionRequest = 2;
  public static final byte SnapshotResponse = 3;

  public static final String[] names = { "NONE", "EnterWorldResponse", "TargetPositionRequest", "SnapshotResponse", };

  public static String name(int e) { return names[e]; }
}

