// automatically generated by the FlatBuffers compiler, do not modify

package forfun.sandbox.uwns.shared.pack.flat;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TargetPositionRequest extends Table {
  public static TargetPositionRequest getRootAsTargetPositionRequest(ByteBuffer _bb) { return getRootAsTargetPositionRequest(_bb, new TargetPositionRequest()); }
  public static TargetPositionRequest getRootAsTargetPositionRequest(ByteBuffer _bb, TargetPositionRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public TargetPositionRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vector position() { return position(new Vector()); }
  public Vector position(Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startTargetPositionRequest(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPosition(FlatBufferBuilder builder, int positionOffset) { builder.addStruct(0, positionOffset, 0); }
  public static int endTargetPositionRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

