// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package forfun.sandbox.uwns.shared.pack.proto;

public interface ActorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Actor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 uid = 1;</code>
   */
  int getUid();

  /**
   * <code>bool active = 2;</code>
   */
  boolean getActive();

  /**
   * <code>.Vector position = 3;</code>
   */
  boolean hasPosition();
  /**
   * <code>.Vector position = 3;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.Vector getPosition();
  /**
   * <code>.Vector position = 3;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder getPositionOrBuilder();
}
