// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package forfun.sandbox.uwns.shared.pack.proto;

public interface AgentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Agent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 uid = 1;</code>
   */
  int getUid();

  /**
   * <code>int32 target_id = 2;</code>
   */
  int getTargetId();

  /**
   * <code>bool active = 3;</code>
   */
  boolean getActive();

  /**
   * <code>.Vector position = 4;</code>
   */
  boolean hasPosition();
  /**
   * <code>.Vector position = 4;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.Vector getPosition();
  /**
   * <code>.Vector position = 4;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder getPositionOrBuilder();

  /**
   * <code>.Vector velocity = 5;</code>
   */
  boolean hasVelocity();
  /**
   * <code>.Vector velocity = 5;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.Vector getVelocity();
  /**
   * <code>.Vector velocity = 5;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder getVelocityOrBuilder();
}
