// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package forfun.sandbox.uwns.shared.pack.proto;

/**
 * Protobuf type {@code Agent}
 */
public  final class Agent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Agent)
    AgentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Agent.newBuilder() to construct.
  private Agent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Agent() {
    uid_ = 0;
    targetId_ = 0;
    active_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Agent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            uid_ = input.readInt32();
            break;
          }
          case 16: {

            targetId_ = input.readInt32();
            break;
          }
          case 24: {

            active_ = input.readBool();
            break;
          }
          case 34: {
                    forfun.sandbox.uwns.shared.pack.proto.Vector.Builder subBuilder = null;
            if (position_ != null) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(forfun.sandbox.uwns.shared.pack.proto.Vector.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
                    forfun.sandbox.uwns.shared.pack.proto.Vector.Builder subBuilder = null;
            if (velocity_ != null) {
              subBuilder = velocity_.toBuilder();
            }
            velocity_ = input.readMessage(forfun.sandbox.uwns.shared.pack.proto.Vector.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(velocity_);
              velocity_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Agent_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Agent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(forfun.sandbox.uwns.shared.pack.proto.Agent.class, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder.class);
  }

  public static final int UID_FIELD_NUMBER = 1;
  private int uid_;
  /**
   * <code>int32 uid = 1;</code>
   */
  public int getUid() {
    return uid_;
  }

  public static final int TARGET_ID_FIELD_NUMBER = 2;
  private int targetId_;
  /**
   * <code>int32 target_id = 2;</code>
   */
  public int getTargetId() {
    return targetId_;
  }

  public static final int ACTIVE_FIELD_NUMBER = 3;
  private boolean active_;
  /**
   * <code>bool active = 3;</code>
   */
  public boolean getActive() {
    return active_;
  }

  public static final int POSITION_FIELD_NUMBER = 4;
  private forfun.sandbox.uwns.shared.pack.proto.Vector position_;
  /**
   * <code>.Vector position = 4;</code>
   */
  public boolean hasPosition() {
    return position_ != null;
  }
  /**
   * <code>.Vector position = 4;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.Vector getPosition() {
    return position_ == null ? forfun.sandbox.uwns.shared.pack.proto.Vector.getDefaultInstance() : position_;
  }
  /**
   * <code>.Vector position = 4;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder getPositionOrBuilder() {
    return getPosition();
  }

  public static final int VELOCITY_FIELD_NUMBER = 5;
  private forfun.sandbox.uwns.shared.pack.proto.Vector velocity_;
  /**
   * <code>.Vector velocity = 5;</code>
   */
  public boolean hasVelocity() {
    return velocity_ != null;
  }
  /**
   * <code>.Vector velocity = 5;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.Vector getVelocity() {
    return velocity_ == null ? forfun.sandbox.uwns.shared.pack.proto.Vector.getDefaultInstance() : velocity_;
  }
  /**
   * <code>.Vector velocity = 5;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder getVelocityOrBuilder() {
    return getVelocity();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uid_ != 0) {
      output.writeInt32(1, uid_);
    }
    if (targetId_ != 0) {
      output.writeInt32(2, targetId_);
    }
    if (active_ != false) {
      output.writeBool(3, active_);
    }
    if (position_ != null) {
      output.writeMessage(4, getPosition());
    }
    if (velocity_ != null) {
      output.writeMessage(5, getVelocity());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, uid_);
    }
    if (targetId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, targetId_);
    }
    if (active_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, active_);
    }
    if (position_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getPosition());
    }
    if (velocity_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getVelocity());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof forfun.sandbox.uwns.shared.pack.proto.Agent)) {
      return super.equals(obj);
    }
        forfun.sandbox.uwns.shared.pack.proto.Agent other = (forfun.sandbox.uwns.shared.pack.proto.Agent) obj;

    boolean result = true;
    result = result && (getUid()
        == other.getUid());
    result = result && (getTargetId()
        == other.getTargetId());
    result = result && (getActive()
        == other.getActive());
    result = result && (hasPosition() == other.hasPosition());
    if (hasPosition()) {
      result = result && getPosition()
          .equals(other.getPosition());
    }
    result = result && (hasVelocity() == other.hasVelocity());
    if (hasVelocity()) {
      result = result && getVelocity()
          .equals(other.getVelocity());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + getUid();
    hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTargetId();
    hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getActive());
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    if (hasVelocity()) {
      hash = (37 * hash) + VELOCITY_FIELD_NUMBER;
      hash = (53 * hash) + getVelocity().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Agent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(forfun.sandbox.uwns.shared.pack.proto.Agent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Agent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Agent)
      forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Agent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Agent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(forfun.sandbox.uwns.shared.pack.proto.Agent.class, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder.class);
    }

    // Construct using forfun.sandbox.uwns.pack.proto.Agent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      uid_ = 0;

      targetId_ = 0;

      active_ = false;

      if (positionBuilder_ == null) {
        position_ = null;
      } else {
        position_ = null;
        positionBuilder_ = null;
      }
      if (velocityBuilder_ == null) {
        velocity_ = null;
      } else {
        velocity_ = null;
        velocityBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Agent_descriptor;
    }

    public forfun.sandbox.uwns.shared.pack.proto.Agent getDefaultInstanceForType() {
      return forfun.sandbox.uwns.shared.pack.proto.Agent.getDefaultInstance();
    }

    public forfun.sandbox.uwns.shared.pack.proto.Agent build() {
            forfun.sandbox.uwns.shared.pack.proto.Agent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public forfun.sandbox.uwns.shared.pack.proto.Agent buildPartial() {
            forfun.sandbox.uwns.shared.pack.proto.Agent result = new forfun.sandbox.uwns.shared.pack.proto.Agent(this);
      result.uid_ = uid_;
      result.targetId_ = targetId_;
      result.active_ = active_;
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      if (velocityBuilder_ == null) {
        result.velocity_ = velocity_;
      } else {
        result.velocity_ = velocityBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof forfun.sandbox.uwns.shared.pack.proto.Agent) {
        return mergeFrom((forfun.sandbox.uwns.shared.pack.proto.Agent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(forfun.sandbox.uwns.shared.pack.proto.Agent other) {
      if (other == forfun.sandbox.uwns.shared.pack.proto.Agent.getDefaultInstance()) return this;
      if (other.getUid() != 0) {
        setUid(other.getUid());
      }
      if (other.getTargetId() != 0) {
        setTargetId(other.getTargetId());
      }
      if (other.getActive() != false) {
        setActive(other.getActive());
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.hasVelocity()) {
        mergeVelocity(other.getVelocity());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
            forfun.sandbox.uwns.shared.pack.proto.Agent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (forfun.sandbox.uwns.shared.pack.proto.Agent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int uid_ ;
    /**
     * <code>int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }
    /**
     * <code>int32 uid = 1;</code>
     */
    public Builder setUid(int value) {
      
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 uid = 1;</code>
     */
    public Builder clearUid() {
      
      uid_ = 0;
      onChanged();
      return this;
    }

    private int targetId_ ;
    /**
     * <code>int32 target_id = 2;</code>
     */
    public int getTargetId() {
      return targetId_;
    }
    /**
     * <code>int32 target_id = 2;</code>
     */
    public Builder setTargetId(int value) {
      
      targetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 target_id = 2;</code>
     */
    public Builder clearTargetId() {
      
      targetId_ = 0;
      onChanged();
      return this;
    }

    private boolean active_ ;
    /**
     * <code>bool active = 3;</code>
     */
    public boolean getActive() {
      return active_;
    }
    /**
     * <code>bool active = 3;</code>
     */
    public Builder setActive(boolean value) {
      
      active_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool active = 3;</code>
     */
    public Builder clearActive() {
      
      active_ = false;
      onChanged();
      return this;
    }

    private forfun.sandbox.uwns.shared.pack.proto.Vector position_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.Vector, forfun.sandbox.uwns.shared.pack.proto.Vector.Builder, forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder> positionBuilder_;
    /**
     * <code>.Vector position = 4;</code>
     */
    public boolean hasPosition() {
      return positionBuilder_ != null || position_ != null;
    }
    /**
     * <code>.Vector position = 4;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Vector getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? forfun.sandbox.uwns.shared.pack.proto.Vector.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.Vector position = 4;</code>
     */
    public Builder setPosition(forfun.sandbox.uwns.shared.pack.proto.Vector value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Vector position = 4;</code>
     */
    public Builder setPosition(
        forfun.sandbox.uwns.shared.pack.proto.Vector.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Vector position = 4;</code>
     */
    public Builder mergePosition(forfun.sandbox.uwns.shared.pack.proto.Vector value) {
      if (positionBuilder_ == null) {
        if (position_ != null) {
          position_ =
                    forfun.sandbox.uwns.shared.pack.proto.Vector.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Vector position = 4;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = null;
        onChanged();
      } else {
        position_ = null;
        positionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Vector position = 4;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Vector.Builder getPositionBuilder() {
      
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.Vector position = 4;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
                forfun.sandbox.uwns.shared.pack.proto.Vector.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.Vector position = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.Vector, forfun.sandbox.uwns.shared.pack.proto.Vector.Builder, forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                forfun.sandbox.uwns.shared.pack.proto.Vector, forfun.sandbox.uwns.shared.pack.proto.Vector.Builder, forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private forfun.sandbox.uwns.shared.pack.proto.Vector velocity_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.Vector, forfun.sandbox.uwns.shared.pack.proto.Vector.Builder, forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder> velocityBuilder_;
    /**
     * <code>.Vector velocity = 5;</code>
     */
    public boolean hasVelocity() {
      return velocityBuilder_ != null || velocity_ != null;
    }
    /**
     * <code>.Vector velocity = 5;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Vector getVelocity() {
      if (velocityBuilder_ == null) {
        return velocity_ == null ? forfun.sandbox.uwns.shared.pack.proto.Vector.getDefaultInstance() : velocity_;
      } else {
        return velocityBuilder_.getMessage();
      }
    }
    /**
     * <code>.Vector velocity = 5;</code>
     */
    public Builder setVelocity(forfun.sandbox.uwns.shared.pack.proto.Vector value) {
      if (velocityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        velocity_ = value;
        onChanged();
      } else {
        velocityBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Vector velocity = 5;</code>
     */
    public Builder setVelocity(
        forfun.sandbox.uwns.shared.pack.proto.Vector.Builder builderForValue) {
      if (velocityBuilder_ == null) {
        velocity_ = builderForValue.build();
        onChanged();
      } else {
        velocityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Vector velocity = 5;</code>
     */
    public Builder mergeVelocity(forfun.sandbox.uwns.shared.pack.proto.Vector value) {
      if (velocityBuilder_ == null) {
        if (velocity_ != null) {
          velocity_ =
                    forfun.sandbox.uwns.shared.pack.proto.Vector.newBuilder(velocity_).mergeFrom(value).buildPartial();
        } else {
          velocity_ = value;
        }
        onChanged();
      } else {
        velocityBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Vector velocity = 5;</code>
     */
    public Builder clearVelocity() {
      if (velocityBuilder_ == null) {
        velocity_ = null;
        onChanged();
      } else {
        velocity_ = null;
        velocityBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Vector velocity = 5;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Vector.Builder getVelocityBuilder() {
      
      onChanged();
      return getVelocityFieldBuilder().getBuilder();
    }
    /**
     * <code>.Vector velocity = 5;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder getVelocityOrBuilder() {
      if (velocityBuilder_ != null) {
        return velocityBuilder_.getMessageOrBuilder();
      } else {
        return velocity_ == null ?
                forfun.sandbox.uwns.shared.pack.proto.Vector.getDefaultInstance() : velocity_;
      }
    }
    /**
     * <code>.Vector velocity = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.Vector, forfun.sandbox.uwns.shared.pack.proto.Vector.Builder, forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder> 
        getVelocityFieldBuilder() {
      if (velocityBuilder_ == null) {
        velocityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                forfun.sandbox.uwns.shared.pack.proto.Vector, forfun.sandbox.uwns.shared.pack.proto.Vector.Builder, forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder>(
                getVelocity(),
                getParentForChildren(),
                isClean());
        velocity_ = null;
      }
      return velocityBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Agent)
  }

  // @@protoc_insertion_point(class_scope:Agent)
  private static final forfun.sandbox.uwns.shared.pack.proto.Agent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new forfun.sandbox.uwns.shared.pack.proto.Agent();
  }

  public static forfun.sandbox.uwns.shared.pack.proto.Agent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Agent>
      PARSER = new com.google.protobuf.AbstractParser<Agent>() {
    public Agent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Agent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Agent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Agent> getParserForType() {
    return PARSER;
  }

  public forfun.sandbox.uwns.shared.pack.proto.Agent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

