// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package forfun.sandbox.uwns.shared.pack.proto;

public interface EnterWorldResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnterWorldResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 uid = 1;</code>
   */
  int getUid();
}
