// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package forfun.sandbox.uwns.shared.pack.proto;

/**
 * Protobuf type {@code Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 842: {
                    forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.Builder subBuilder = null;
            if (requestCase_ == 105) {
              subBuilder = ((forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse) request_).toBuilder();
            }
            request_ =
                input.readMessage(forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 105;
            break;
          }
          case 882: {
                    forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.Builder subBuilder = null;
            if (requestCase_ == 110) {
              subBuilder = ((forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest) request_).toBuilder();
            }
            request_ =
                input.readMessage(forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 110;
            break;
          }
          case 922: {
                    forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.Builder subBuilder = null;
            if (requestCase_ == 115) {
              subBuilder = ((forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) request_).toBuilder();
            }
            request_ =
                input.readMessage(forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) request_);
              request_ = subBuilder.buildPartial();
            }
            requestCase_ = 115;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Message_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(forfun.sandbox.uwns.shared.pack.proto.Message.class, forfun.sandbox.uwns.shared.pack.proto.Message.Builder.class);
  }

  private int requestCase_ = 0;
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite {
    ENTER_WORLD_RESPONSE(105),
    TARGET_POSITION_REQUEST(110),
    SNAPSHOT_RESPONSE(115),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 105: return ENTER_WORLD_RESPONSE;
        case 110: return TARGET_POSITION_REQUEST;
        case 115: return SNAPSHOT_RESPONSE;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  public static final int ENTER_WORLD_RESPONSE_FIELD_NUMBER = 105;
  /**
   * <code>.EnterWorldResponse enter_world_response = 105;</code>
   */
  public boolean hasEnterWorldResponse() {
    return requestCase_ == 105;
  }
  /**
   * <code>.EnterWorldResponse enter_world_response = 105;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse getEnterWorldResponse() {
    if (requestCase_ == 105) {
       return (forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse) request_;
    }
    return forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.getDefaultInstance();
  }
  /**
   * <code>.EnterWorldResponse enter_world_response = 105;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponseOrBuilder getEnterWorldResponseOrBuilder() {
    if (requestCase_ == 105) {
       return (forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse) request_;
    }
    return forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.getDefaultInstance();
  }

  public static final int TARGET_POSITION_REQUEST_FIELD_NUMBER = 110;
  /**
   * <code>.TargetPositionRequest target_position_request = 110;</code>
   */
  public boolean hasTargetPositionRequest() {
    return requestCase_ == 110;
  }
  /**
   * <code>.TargetPositionRequest target_position_request = 110;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest getTargetPositionRequest() {
    if (requestCase_ == 110) {
       return (forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest) request_;
    }
    return forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.getDefaultInstance();
  }
  /**
   * <code>.TargetPositionRequest target_position_request = 110;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequestOrBuilder getTargetPositionRequestOrBuilder() {
    if (requestCase_ == 110) {
       return (forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest) request_;
    }
    return forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.getDefaultInstance();
  }

  public static final int SNAPSHOT_RESPONSE_FIELD_NUMBER = 115;
  /**
   * <code>.SnapshotResponse snapshot_response = 115;</code>
   */
  public boolean hasSnapshotResponse() {
    return requestCase_ == 115;
  }
  /**
   * <code>.SnapshotResponse snapshot_response = 115;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse getSnapshotResponse() {
    if (requestCase_ == 115) {
       return (forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) request_;
    }
    return forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.getDefaultInstance();
  }
  /**
   * <code>.SnapshotResponse snapshot_response = 115;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.SnapshotResponseOrBuilder getSnapshotResponseOrBuilder() {
    if (requestCase_ == 115) {
       return (forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) request_;
    }
    return forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 105) {
      output.writeMessage(105, (forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse) request_);
    }
    if (requestCase_ == 110) {
      output.writeMessage(110, (forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest) request_);
    }
    if (requestCase_ == 115) {
      output.writeMessage(115, (forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) request_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 105) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(105, (forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse) request_);
    }
    if (requestCase_ == 110) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(110, (forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest) request_);
    }
    if (requestCase_ == 115) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(115, (forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) request_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof forfun.sandbox.uwns.shared.pack.proto.Message)) {
      return super.equals(obj);
    }
        forfun.sandbox.uwns.shared.pack.proto.Message other = (forfun.sandbox.uwns.shared.pack.proto.Message) obj;

    boolean result = true;
    result = result && getRequestCase().equals(
        other.getRequestCase());
    if (!result) return false;
    switch (requestCase_) {
      case 105:
        result = result && getEnterWorldResponse()
            .equals(other.getEnterWorldResponse());
        break;
      case 110:
        result = result && getTargetPositionRequest()
            .equals(other.getTargetPositionRequest());
        break;
      case 115:
        result = result && getSnapshotResponse()
            .equals(other.getSnapshotResponse());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (requestCase_) {
      case 105:
        hash = (37 * hash) + ENTER_WORLD_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getEnterWorldResponse().hashCode();
        break;
      case 110:
        hash = (37 * hash) + TARGET_POSITION_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getTargetPositionRequest().hashCode();
        break;
      case 115:
        hash = (37 * hash) + SNAPSHOT_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getSnapshotResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static forfun.sandbox.uwns.shared.pack.proto.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(forfun.sandbox.uwns.shared.pack.proto.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message)
      forfun.sandbox.uwns.shared.pack.proto.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(forfun.sandbox.uwns.shared.pack.proto.Message.class, forfun.sandbox.uwns.shared.pack.proto.Message.Builder.class);
    }

    // Construct using forfun.sandbox.uwns.pack.proto.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      requestCase_ = 0;
      request_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Message_descriptor;
    }

    public forfun.sandbox.uwns.shared.pack.proto.Message getDefaultInstanceForType() {
      return forfun.sandbox.uwns.shared.pack.proto.Message.getDefaultInstance();
    }

    public forfun.sandbox.uwns.shared.pack.proto.Message build() {
            forfun.sandbox.uwns.shared.pack.proto.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public forfun.sandbox.uwns.shared.pack.proto.Message buildPartial() {
            forfun.sandbox.uwns.shared.pack.proto.Message result = new forfun.sandbox.uwns.shared.pack.proto.Message(this);
      if (requestCase_ == 105) {
        if (enterWorldResponseBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = enterWorldResponseBuilder_.build();
        }
      }
      if (requestCase_ == 110) {
        if (targetPositionRequestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = targetPositionRequestBuilder_.build();
        }
      }
      if (requestCase_ == 115) {
        if (snapshotResponseBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = snapshotResponseBuilder_.build();
        }
      }
      result.requestCase_ = requestCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof forfun.sandbox.uwns.shared.pack.proto.Message) {
        return mergeFrom((forfun.sandbox.uwns.shared.pack.proto.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(forfun.sandbox.uwns.shared.pack.proto.Message other) {
      if (other == forfun.sandbox.uwns.shared.pack.proto.Message.getDefaultInstance()) return this;
      switch (other.getRequestCase()) {
        case ENTER_WORLD_RESPONSE: {
          mergeEnterWorldResponse(other.getEnterWorldResponse());
          break;
        }
        case TARGET_POSITION_REQUEST: {
          mergeTargetPositionRequest(other.getTargetPositionRequest());
          break;
        }
        case SNAPSHOT_RESPONSE: {
          mergeSnapshotResponse(other.getSnapshotResponse());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
            forfun.sandbox.uwns.shared.pack.proto.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (forfun.sandbox.uwns.shared.pack.proto.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse, forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.Builder, forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponseOrBuilder> enterWorldResponseBuilder_;
    /**
     * <code>.EnterWorldResponse enter_world_response = 105;</code>
     */
    public boolean hasEnterWorldResponse() {
      return requestCase_ == 105;
    }
    /**
     * <code>.EnterWorldResponse enter_world_response = 105;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse getEnterWorldResponse() {
      if (enterWorldResponseBuilder_ == null) {
        if (requestCase_ == 105) {
          return (  forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse) request_;
        }
        return  forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.getDefaultInstance();
      } else {
        if (requestCase_ == 105) {
          return enterWorldResponseBuilder_.getMessage();
        }
        return  forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.EnterWorldResponse enter_world_response = 105;</code>
     */
    public Builder setEnterWorldResponse(forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse value) {
      if (enterWorldResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        enterWorldResponseBuilder_.setMessage(value);
      }
      requestCase_ = 105;
      return this;
    }
    /**
     * <code>.EnterWorldResponse enter_world_response = 105;</code>
     */
    public Builder setEnterWorldResponse(
        forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.Builder builderForValue) {
      if (enterWorldResponseBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        enterWorldResponseBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 105;
      return this;
    }
    /**
     * <code>.EnterWorldResponse enter_world_response = 105;</code>
     */
    public Builder mergeEnterWorldResponse(forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse value) {
      if (enterWorldResponseBuilder_ == null) {
        if (requestCase_ == 105 &&
            request_ != forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.getDefaultInstance()) {
          request_ = forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.newBuilder((forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 105) {
          enterWorldResponseBuilder_.mergeFrom(value);
        }
        enterWorldResponseBuilder_.setMessage(value);
      }
      requestCase_ = 105;
      return this;
    }
    /**
     * <code>.EnterWorldResponse enter_world_response = 105;</code>
     */
    public Builder clearEnterWorldResponse() {
      if (enterWorldResponseBuilder_ == null) {
        if (requestCase_ == 105) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 105) {
          requestCase_ = 0;
          request_ = null;
        }
        enterWorldResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.EnterWorldResponse enter_world_response = 105;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.Builder getEnterWorldResponseBuilder() {
      return getEnterWorldResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.EnterWorldResponse enter_world_response = 105;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponseOrBuilder getEnterWorldResponseOrBuilder() {
      if ((requestCase_ == 105) && (enterWorldResponseBuilder_ != null)) {
        return enterWorldResponseBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 105) {
          return (  forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse) request_;
        }
        return  forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.EnterWorldResponse enter_world_response = 105;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse, forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.Builder, forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponseOrBuilder> 
        getEnterWorldResponseFieldBuilder() {
      if (enterWorldResponseBuilder_ == null) {
        if (!(requestCase_ == 105)) {
          request_ = forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.getDefaultInstance();
        }
        enterWorldResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse, forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse.Builder, forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponseOrBuilder>(
                (forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 105;
      onChanged();;
      return enterWorldResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest, forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.Builder, forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequestOrBuilder> targetPositionRequestBuilder_;
    /**
     * <code>.TargetPositionRequest target_position_request = 110;</code>
     */
    public boolean hasTargetPositionRequest() {
      return requestCase_ == 110;
    }
    /**
     * <code>.TargetPositionRequest target_position_request = 110;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest getTargetPositionRequest() {
      if (targetPositionRequestBuilder_ == null) {
        if (requestCase_ == 110) {
          return (  forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest) request_;
        }
        return  forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 110) {
          return targetPositionRequestBuilder_.getMessage();
        }
        return  forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.TargetPositionRequest target_position_request = 110;</code>
     */
    public Builder setTargetPositionRequest(forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest value) {
      if (targetPositionRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        targetPositionRequestBuilder_.setMessage(value);
      }
      requestCase_ = 110;
      return this;
    }
    /**
     * <code>.TargetPositionRequest target_position_request = 110;</code>
     */
    public Builder setTargetPositionRequest(
        forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.Builder builderForValue) {
      if (targetPositionRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        targetPositionRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 110;
      return this;
    }
    /**
     * <code>.TargetPositionRequest target_position_request = 110;</code>
     */
    public Builder mergeTargetPositionRequest(forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest value) {
      if (targetPositionRequestBuilder_ == null) {
        if (requestCase_ == 110 &&
            request_ != forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.getDefaultInstance()) {
          request_ = forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.newBuilder((forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 110) {
          targetPositionRequestBuilder_.mergeFrom(value);
        }
        targetPositionRequestBuilder_.setMessage(value);
      }
      requestCase_ = 110;
      return this;
    }
    /**
     * <code>.TargetPositionRequest target_position_request = 110;</code>
     */
    public Builder clearTargetPositionRequest() {
      if (targetPositionRequestBuilder_ == null) {
        if (requestCase_ == 110) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 110) {
          requestCase_ = 0;
          request_ = null;
        }
        targetPositionRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.TargetPositionRequest target_position_request = 110;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.Builder getTargetPositionRequestBuilder() {
      return getTargetPositionRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.TargetPositionRequest target_position_request = 110;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequestOrBuilder getTargetPositionRequestOrBuilder() {
      if ((requestCase_ == 110) && (targetPositionRequestBuilder_ != null)) {
        return targetPositionRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 110) {
          return (  forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest) request_;
        }
        return  forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.TargetPositionRequest target_position_request = 110;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest, forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.Builder, forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequestOrBuilder> 
        getTargetPositionRequestFieldBuilder() {
      if (targetPositionRequestBuilder_ == null) {
        if (!(requestCase_ == 110)) {
          request_ = forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.getDefaultInstance();
        }
        targetPositionRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest, forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest.Builder, forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequestOrBuilder>(
                (forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 110;
      onChanged();;
      return targetPositionRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse, forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.Builder, forfun.sandbox.uwns.shared.pack.proto.SnapshotResponseOrBuilder> snapshotResponseBuilder_;
    /**
     * <code>.SnapshotResponse snapshot_response = 115;</code>
     */
    public boolean hasSnapshotResponse() {
      return requestCase_ == 115;
    }
    /**
     * <code>.SnapshotResponse snapshot_response = 115;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse getSnapshotResponse() {
      if (snapshotResponseBuilder_ == null) {
        if (requestCase_ == 115) {
          return (  forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) request_;
        }
        return  forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.getDefaultInstance();
      } else {
        if (requestCase_ == 115) {
          return snapshotResponseBuilder_.getMessage();
        }
        return  forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.SnapshotResponse snapshot_response = 115;</code>
     */
    public Builder setSnapshotResponse(forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse value) {
      if (snapshotResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        snapshotResponseBuilder_.setMessage(value);
      }
      requestCase_ = 115;
      return this;
    }
    /**
     * <code>.SnapshotResponse snapshot_response = 115;</code>
     */
    public Builder setSnapshotResponse(
        forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.Builder builderForValue) {
      if (snapshotResponseBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        snapshotResponseBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 115;
      return this;
    }
    /**
     * <code>.SnapshotResponse snapshot_response = 115;</code>
     */
    public Builder mergeSnapshotResponse(forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse value) {
      if (snapshotResponseBuilder_ == null) {
        if (requestCase_ == 115 &&
            request_ != forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.getDefaultInstance()) {
          request_ = forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.newBuilder((forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 115) {
          snapshotResponseBuilder_.mergeFrom(value);
        }
        snapshotResponseBuilder_.setMessage(value);
      }
      requestCase_ = 115;
      return this;
    }
    /**
     * <code>.SnapshotResponse snapshot_response = 115;</code>
     */
    public Builder clearSnapshotResponse() {
      if (snapshotResponseBuilder_ == null) {
        if (requestCase_ == 115) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 115) {
          requestCase_ = 0;
          request_ = null;
        }
        snapshotResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.SnapshotResponse snapshot_response = 115;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.Builder getSnapshotResponseBuilder() {
      return getSnapshotResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.SnapshotResponse snapshot_response = 115;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.SnapshotResponseOrBuilder getSnapshotResponseOrBuilder() {
      if ((requestCase_ == 115) && (snapshotResponseBuilder_ != null)) {
        return snapshotResponseBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 115) {
          return (  forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) request_;
        }
        return  forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.SnapshotResponse snapshot_response = 115;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse, forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.Builder, forfun.sandbox.uwns.shared.pack.proto.SnapshotResponseOrBuilder> 
        getSnapshotResponseFieldBuilder() {
      if (snapshotResponseBuilder_ == null) {
        if (!(requestCase_ == 115)) {
          request_ = forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.getDefaultInstance();
        }
        snapshotResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse, forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.Builder, forfun.sandbox.uwns.shared.pack.proto.SnapshotResponseOrBuilder>(
                (forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 115;
      onChanged();;
      return snapshotResponseBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message)
  }

  // @@protoc_insertion_point(class_scope:Message)
  private static final forfun.sandbox.uwns.shared.pack.proto.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new forfun.sandbox.uwns.shared.pack.proto.Message();
  }

  public static forfun.sandbox.uwns.shared.pack.proto.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  public forfun.sandbox.uwns.shared.pack.proto.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

