// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package forfun.sandbox.uwns.shared.pack.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.EnterWorldResponse enter_world_response = 105;</code>
   */
  boolean hasEnterWorldResponse();
  /**
   * <code>.EnterWorldResponse enter_world_response = 105;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponse getEnterWorldResponse();
  /**
   * <code>.EnterWorldResponse enter_world_response = 105;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.EnterWorldResponseOrBuilder getEnterWorldResponseOrBuilder();

  /**
   * <code>.TargetPositionRequest target_position_request = 110;</code>
   */
  boolean hasTargetPositionRequest();
  /**
   * <code>.TargetPositionRequest target_position_request = 110;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequest getTargetPositionRequest();
  /**
   * <code>.TargetPositionRequest target_position_request = 110;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.TargetPositionRequestOrBuilder getTargetPositionRequestOrBuilder();

  /**
   * <code>.SnapshotResponse snapshot_response = 115;</code>
   */
  boolean hasSnapshotResponse();
  /**
   * <code>.SnapshotResponse snapshot_response = 115;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse getSnapshotResponse();
  /**
   * <code>.SnapshotResponse snapshot_response = 115;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.SnapshotResponseOrBuilder getSnapshotResponseOrBuilder();

  public forfun.sandbox.uwns.shared.pack.proto.Message.RequestCase getRequestCase();
}
