// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package forfun.sandbox.uwns.shared.pack.proto;

public interface SnapshotResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SnapshotResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float radius = 1;</code>
   */
  float getRadius();

  /**
   * <code>repeated .Actor targets = 2;</code>
   */
  java.util.List<forfun.sandbox.uwns.shared.pack.proto.Actor> 
      getTargetsList();
  /**
   * <code>repeated .Actor targets = 2;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.Actor getTargets(int index);
  /**
   * <code>repeated .Actor targets = 2;</code>
   */
  int getTargetsCount();
  /**
   * <code>repeated .Actor targets = 2;</code>
   */
  java.util.List<? extends forfun.sandbox.uwns.shared.pack.proto.ActorOrBuilder> 
      getTargetsOrBuilderList();
  /**
   * <code>repeated .Actor targets = 2;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.ActorOrBuilder getTargetsOrBuilder(
      int index);

  /**
   * <code>repeated .Agent players = 3;</code>
   */
  java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent> 
      getPlayersList();
  /**
   * <code>repeated .Agent players = 3;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.Agent getPlayers(int index);
  /**
   * <code>repeated .Agent players = 3;</code>
   */
  int getPlayersCount();
  /**
   * <code>repeated .Agent players = 3;</code>
   */
  java.util.List<? extends forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <code>repeated .Agent players = 3;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder getPlayersOrBuilder(
      int index);

  /**
   * <code>repeated .Agent non_players = 4;</code>
   */
  java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent> 
      getNonPlayersList();
  /**
   * <code>repeated .Agent non_players = 4;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.Agent getNonPlayers(int index);
  /**
   * <code>repeated .Agent non_players = 4;</code>
   */
  int getNonPlayersCount();
  /**
   * <code>repeated .Agent non_players = 4;</code>
   */
  java.util.List<? extends forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder> 
      getNonPlayersOrBuilderList();
  /**
   * <code>repeated .Agent non_players = 4;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder getNonPlayersOrBuilder(
      int index);
}
