// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package forfun.sandbox.uwns.shared.pack.proto;

/**
 * Protobuf type {@code SnapshotResponse}
 */
public  final class SnapshotResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SnapshotResponse)
    SnapshotResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SnapshotResponse.newBuilder() to construct.
  private SnapshotResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SnapshotResponse() {
    radius_ = 0F;
    targets_ = java.util.Collections.emptyList();
    players_ = java.util.Collections.emptyList();
    nonPlayers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SnapshotResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 13: {

            radius_ = input.readFloat();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              targets_ = new java.util.ArrayList<forfun.sandbox.uwns.shared.pack.proto.Actor>();
              mutable_bitField0_ |= 0x00000002;
            }
            targets_.add(input.readMessage(forfun.sandbox.uwns.shared.pack.proto.Actor.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              players_ = new java.util.ArrayList<forfun.sandbox.uwns.shared.pack.proto.Agent>();
              mutable_bitField0_ |= 0x00000004;
            }
            players_.add(input.readMessage(forfun.sandbox.uwns.shared.pack.proto.Agent.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              nonPlayers_ = new java.util.ArrayList<forfun.sandbox.uwns.shared.pack.proto.Agent>();
              mutable_bitField0_ |= 0x00000008;
            }
            nonPlayers_.add(input.readMessage(forfun.sandbox.uwns.shared.pack.proto.Agent.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        targets_ = java.util.Collections.unmodifiableList(targets_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        players_ = java.util.Collections.unmodifiableList(players_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        nonPlayers_ = java.util.Collections.unmodifiableList(nonPlayers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_SnapshotResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_SnapshotResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.class, forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RADIUS_FIELD_NUMBER = 1;
  private float radius_;
  /**
   * <code>float radius = 1;</code>
   */
  public float getRadius() {
    return radius_;
  }

  public static final int TARGETS_FIELD_NUMBER = 2;
  private java.util.List<forfun.sandbox.uwns.shared.pack.proto.Actor> targets_;
  /**
   * <code>repeated .Actor targets = 2;</code>
   */
  public java.util.List<forfun.sandbox.uwns.shared.pack.proto.Actor> getTargetsList() {
    return targets_;
  }
  /**
   * <code>repeated .Actor targets = 2;</code>
   */
  public java.util.List<? extends forfun.sandbox.uwns.shared.pack.proto.ActorOrBuilder> 
      getTargetsOrBuilderList() {
    return targets_;
  }
  /**
   * <code>repeated .Actor targets = 2;</code>
   */
  public int getTargetsCount() {
    return targets_.size();
  }
  /**
   * <code>repeated .Actor targets = 2;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.Actor getTargets(int index) {
    return targets_.get(index);
  }
  /**
   * <code>repeated .Actor targets = 2;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.ActorOrBuilder getTargetsOrBuilder(
      int index) {
    return targets_.get(index);
  }

  public static final int PLAYERS_FIELD_NUMBER = 3;
  private java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent> players_;
  /**
   * <code>repeated .Agent players = 3;</code>
   */
  public java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent> getPlayersList() {
    return players_;
  }
  /**
   * <code>repeated .Agent players = 3;</code>
   */
  public java.util.List<? extends forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder> 
      getPlayersOrBuilderList() {
    return players_;
  }
  /**
   * <code>repeated .Agent players = 3;</code>
   */
  public int getPlayersCount() {
    return players_.size();
  }
  /**
   * <code>repeated .Agent players = 3;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.Agent getPlayers(int index) {
    return players_.get(index);
  }
  /**
   * <code>repeated .Agent players = 3;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder getPlayersOrBuilder(
      int index) {
    return players_.get(index);
  }

  public static final int NON_PLAYERS_FIELD_NUMBER = 4;
  private java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent> nonPlayers_;
  /**
   * <code>repeated .Agent non_players = 4;</code>
   */
  public java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent> getNonPlayersList() {
    return nonPlayers_;
  }
  /**
   * <code>repeated .Agent non_players = 4;</code>
   */
  public java.util.List<? extends forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder> 
      getNonPlayersOrBuilderList() {
    return nonPlayers_;
  }
  /**
   * <code>repeated .Agent non_players = 4;</code>
   */
  public int getNonPlayersCount() {
    return nonPlayers_.size();
  }
  /**
   * <code>repeated .Agent non_players = 4;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.Agent getNonPlayers(int index) {
    return nonPlayers_.get(index);
  }
  /**
   * <code>repeated .Agent non_players = 4;</code>
   */
  public forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder getNonPlayersOrBuilder(
      int index) {
    return nonPlayers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (radius_ != 0F) {
      output.writeFloat(1, radius_);
    }
    for (int i = 0; i < targets_.size(); i++) {
      output.writeMessage(2, targets_.get(i));
    }
    for (int i = 0; i < players_.size(); i++) {
      output.writeMessage(3, players_.get(i));
    }
    for (int i = 0; i < nonPlayers_.size(); i++) {
      output.writeMessage(4, nonPlayers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (radius_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, radius_);
    }
    for (int i = 0; i < targets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, targets_.get(i));
    }
    for (int i = 0; i < players_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, players_.get(i));
    }
    for (int i = 0; i < nonPlayers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, nonPlayers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse)) {
      return super.equals(obj);
    }
        forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse other = (forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getRadius())
        == java.lang.Float.floatToIntBits(
            other.getRadius()));
    result = result && getTargetsList()
        .equals(other.getTargetsList());
    result = result && getPlayersList()
        .equals(other.getPlayersList());
    result = result && getNonPlayersList()
        .equals(other.getNonPlayersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RADIUS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getRadius());
    if (getTargetsCount() > 0) {
      hash = (37 * hash) + TARGETS_FIELD_NUMBER;
      hash = (53 * hash) + getTargetsList().hashCode();
    }
    if (getPlayersCount() > 0) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayersList().hashCode();
    }
    if (getNonPlayersCount() > 0) {
      hash = (37 * hash) + NON_PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getNonPlayersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SnapshotResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SnapshotResponse)
      forfun.sandbox.uwns.shared.pack.proto.SnapshotResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_SnapshotResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_SnapshotResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.class, forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.Builder.class);
    }

    // Construct using forfun.sandbox.uwns.pack.proto.SnapshotResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTargetsFieldBuilder();
        getPlayersFieldBuilder();
        getNonPlayersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      radius_ = 0F;

      if (targetsBuilder_ == null) {
        targets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        targetsBuilder_.clear();
      }
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        playersBuilder_.clear();
      }
      if (nonPlayersBuilder_ == null) {
        nonPlayers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        nonPlayersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_SnapshotResponse_descriptor;
    }

    public forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse getDefaultInstanceForType() {
      return forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.getDefaultInstance();
    }

    public forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse build() {
            forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse buildPartial() {
            forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse result = new forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.radius_ = radius_;
      if (targetsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          targets_ = java.util.Collections.unmodifiableList(targets_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.targets_ = targets_;
      } else {
        result.targets_ = targetsBuilder_.build();
      }
      if (playersBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          players_ = java.util.Collections.unmodifiableList(players_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.players_ = players_;
      } else {
        result.players_ = playersBuilder_.build();
      }
      if (nonPlayersBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          nonPlayers_ = java.util.Collections.unmodifiableList(nonPlayers_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.nonPlayers_ = nonPlayers_;
      } else {
        result.nonPlayers_ = nonPlayersBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) {
        return mergeFrom((forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse other) {
      if (other == forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse.getDefaultInstance()) return this;
      if (other.getRadius() != 0F) {
        setRadius(other.getRadius());
      }
      if (targetsBuilder_ == null) {
        if (!other.targets_.isEmpty()) {
          if (targets_.isEmpty()) {
            targets_ = other.targets_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTargetsIsMutable();
            targets_.addAll(other.targets_);
          }
          onChanged();
        }
      } else {
        if (!other.targets_.isEmpty()) {
          if (targetsBuilder_.isEmpty()) {
            targetsBuilder_.dispose();
            targetsBuilder_ = null;
            targets_ = other.targets_;
            bitField0_ = (bitField0_ & ~0x00000002);
            targetsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTargetsFieldBuilder() : null;
          } else {
            targetsBuilder_.addAllMessages(other.targets_);
          }
        }
      }
      if (playersBuilder_ == null) {
        if (!other.players_.isEmpty()) {
          if (players_.isEmpty()) {
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePlayersIsMutable();
            players_.addAll(other.players_);
          }
          onChanged();
        }
      } else {
        if (!other.players_.isEmpty()) {
          if (playersBuilder_.isEmpty()) {
            playersBuilder_.dispose();
            playersBuilder_ = null;
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000004);
            playersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPlayersFieldBuilder() : null;
          } else {
            playersBuilder_.addAllMessages(other.players_);
          }
        }
      }
      if (nonPlayersBuilder_ == null) {
        if (!other.nonPlayers_.isEmpty()) {
          if (nonPlayers_.isEmpty()) {
            nonPlayers_ = other.nonPlayers_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureNonPlayersIsMutable();
            nonPlayers_.addAll(other.nonPlayers_);
          }
          onChanged();
        }
      } else {
        if (!other.nonPlayers_.isEmpty()) {
          if (nonPlayersBuilder_.isEmpty()) {
            nonPlayersBuilder_.dispose();
            nonPlayersBuilder_ = null;
            nonPlayers_ = other.nonPlayers_;
            bitField0_ = (bitField0_ & ~0x00000008);
            nonPlayersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNonPlayersFieldBuilder() : null;
          } else {
            nonPlayersBuilder_.addAllMessages(other.nonPlayers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
            forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private float radius_ ;
    /**
     * <code>float radius = 1;</code>
     */
    public float getRadius() {
      return radius_;
    }
    /**
     * <code>float radius = 1;</code>
     */
    public Builder setRadius(float value) {
      
      radius_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float radius = 1;</code>
     */
    public Builder clearRadius() {
      
      radius_ = 0F;
      onChanged();
      return this;
    }

    private java.util.List<forfun.sandbox.uwns.shared.pack.proto.Actor> targets_ =
      java.util.Collections.emptyList();
    private void ensureTargetsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        targets_ = new java.util.ArrayList<forfun.sandbox.uwns.shared.pack.proto.Actor>(targets_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.Actor, forfun.sandbox.uwns.shared.pack.proto.Actor.Builder, forfun.sandbox.uwns.shared.pack.proto.ActorOrBuilder> targetsBuilder_;

    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public java.util.List<forfun.sandbox.uwns.shared.pack.proto.Actor> getTargetsList() {
      if (targetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(targets_);
      } else {
        return targetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public int getTargetsCount() {
      if (targetsBuilder_ == null) {
        return targets_.size();
      } else {
        return targetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Actor getTargets(int index) {
      if (targetsBuilder_ == null) {
        return targets_.get(index);
      } else {
        return targetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public Builder setTargets(
        int index, forfun.sandbox.uwns.shared.pack.proto.Actor value) {
      if (targetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetsIsMutable();
        targets_.set(index, value);
        onChanged();
      } else {
        targetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public Builder setTargets(
        int index, forfun.sandbox.uwns.shared.pack.proto.Actor.Builder builderForValue) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.set(index, builderForValue.build());
        onChanged();
      } else {
        targetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public Builder addTargets(forfun.sandbox.uwns.shared.pack.proto.Actor value) {
      if (targetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetsIsMutable();
        targets_.add(value);
        onChanged();
      } else {
        targetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public Builder addTargets(
        int index, forfun.sandbox.uwns.shared.pack.proto.Actor value) {
      if (targetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTargetsIsMutable();
        targets_.add(index, value);
        onChanged();
      } else {
        targetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public Builder addTargets(
        forfun.sandbox.uwns.shared.pack.proto.Actor.Builder builderForValue) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.add(builderForValue.build());
        onChanged();
      } else {
        targetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public Builder addTargets(
        int index, forfun.sandbox.uwns.shared.pack.proto.Actor.Builder builderForValue) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.add(index, builderForValue.build());
        onChanged();
      } else {
        targetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public Builder addAllTargets(
        java.lang.Iterable<? extends forfun.sandbox.uwns.shared.pack.proto.Actor> values) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, targets_);
        onChanged();
      } else {
        targetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public Builder clearTargets() {
      if (targetsBuilder_ == null) {
        targets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        targetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public Builder removeTargets(int index) {
      if (targetsBuilder_ == null) {
        ensureTargetsIsMutable();
        targets_.remove(index);
        onChanged();
      } else {
        targetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Actor.Builder getTargetsBuilder(
        int index) {
      return getTargetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.ActorOrBuilder getTargetsOrBuilder(
        int index) {
      if (targetsBuilder_ == null) {
        return targets_.get(index);  } else {
        return targetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public java.util.List<? extends forfun.sandbox.uwns.shared.pack.proto.ActorOrBuilder> 
         getTargetsOrBuilderList() {
      if (targetsBuilder_ != null) {
        return targetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(targets_);
      }
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Actor.Builder addTargetsBuilder() {
      return getTargetsFieldBuilder().addBuilder(forfun.sandbox.uwns.shared.pack.proto.Actor.getDefaultInstance());
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Actor.Builder addTargetsBuilder(
        int index) {
      return getTargetsFieldBuilder().addBuilder(index, forfun.sandbox.uwns.shared.pack.proto.Actor.getDefaultInstance());
    }
    /**
     * <code>repeated .Actor targets = 2;</code>
     */
    public java.util.List<forfun.sandbox.uwns.shared.pack.proto.Actor.Builder> 
         getTargetsBuilderList() {
      return getTargetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.Actor, forfun.sandbox.uwns.shared.pack.proto.Actor.Builder, forfun.sandbox.uwns.shared.pack.proto.ActorOrBuilder> 
        getTargetsFieldBuilder() {
      if (targetsBuilder_ == null) {
        targetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                forfun.sandbox.uwns.shared.pack.proto.Actor, forfun.sandbox.uwns.shared.pack.proto.Actor.Builder, forfun.sandbox.uwns.shared.pack.proto.ActorOrBuilder>(
                targets_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        targets_ = null;
      }
      return targetsBuilder_;
    }

    private java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent> players_ =
      java.util.Collections.emptyList();
    private void ensurePlayersIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        players_ = new java.util.ArrayList<forfun.sandbox.uwns.shared.pack.proto.Agent>(players_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.Agent, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder, forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder> playersBuilder_;

    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent> getPlayersList() {
      if (playersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(players_);
      } else {
        return playersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public int getPlayersCount() {
      if (playersBuilder_ == null) {
        return players_.size();
      } else {
        return playersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Agent getPlayers(int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);
      } else {
        return playersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public Builder setPlayers(
        int index, forfun.sandbox.uwns.shared.pack.proto.Agent value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.set(index, value);
        onChanged();
      } else {
        playersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public Builder setPlayers(
        int index, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.set(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public Builder addPlayers(forfun.sandbox.uwns.shared.pack.proto.Agent value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(value);
        onChanged();
      } else {
        playersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public Builder addPlayers(
        int index, forfun.sandbox.uwns.shared.pack.proto.Agent value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(index, value);
        onChanged();
      } else {
        playersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public Builder addPlayers(
        forfun.sandbox.uwns.shared.pack.proto.Agent.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public Builder addPlayers(
        int index, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public Builder addAllPlayers(
        java.lang.Iterable<? extends forfun.sandbox.uwns.shared.pack.proto.Agent> values) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, players_);
        onChanged();
      } else {
        playersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public Builder clearPlayers() {
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        playersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public Builder removePlayers(int index) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.remove(index);
        onChanged();
      } else {
        playersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Agent.Builder getPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder getPlayersOrBuilder(
        int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);  } else {
        return playersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public java.util.List<? extends forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder> 
         getPlayersOrBuilderList() {
      if (playersBuilder_ != null) {
        return playersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(players_);
      }
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Agent.Builder addPlayersBuilder() {
      return getPlayersFieldBuilder().addBuilder(forfun.sandbox.uwns.shared.pack.proto.Agent.getDefaultInstance());
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Agent.Builder addPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().addBuilder(index, forfun.sandbox.uwns.shared.pack.proto.Agent.getDefaultInstance());
    }
    /**
     * <code>repeated .Agent players = 3;</code>
     */
    public java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent.Builder> 
         getPlayersBuilderList() {
      return getPlayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.Agent, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder, forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder> 
        getPlayersFieldBuilder() {
      if (playersBuilder_ == null) {
        playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                forfun.sandbox.uwns.shared.pack.proto.Agent, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder, forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder>(
                players_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        players_ = null;
      }
      return playersBuilder_;
    }

    private java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent> nonPlayers_ =
      java.util.Collections.emptyList();
    private void ensureNonPlayersIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        nonPlayers_ = new java.util.ArrayList<forfun.sandbox.uwns.shared.pack.proto.Agent>(nonPlayers_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.Agent, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder, forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder> nonPlayersBuilder_;

    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent> getNonPlayersList() {
      if (nonPlayersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(nonPlayers_);
      } else {
        return nonPlayersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public int getNonPlayersCount() {
      if (nonPlayersBuilder_ == null) {
        return nonPlayers_.size();
      } else {
        return nonPlayersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Agent getNonPlayers(int index) {
      if (nonPlayersBuilder_ == null) {
        return nonPlayers_.get(index);
      } else {
        return nonPlayersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public Builder setNonPlayers(
        int index, forfun.sandbox.uwns.shared.pack.proto.Agent value) {
      if (nonPlayersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNonPlayersIsMutable();
        nonPlayers_.set(index, value);
        onChanged();
      } else {
        nonPlayersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public Builder setNonPlayers(
        int index, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder builderForValue) {
      if (nonPlayersBuilder_ == null) {
        ensureNonPlayersIsMutable();
        nonPlayers_.set(index, builderForValue.build());
        onChanged();
      } else {
        nonPlayersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public Builder addNonPlayers(forfun.sandbox.uwns.shared.pack.proto.Agent value) {
      if (nonPlayersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNonPlayersIsMutable();
        nonPlayers_.add(value);
        onChanged();
      } else {
        nonPlayersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public Builder addNonPlayers(
        int index, forfun.sandbox.uwns.shared.pack.proto.Agent value) {
      if (nonPlayersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNonPlayersIsMutable();
        nonPlayers_.add(index, value);
        onChanged();
      } else {
        nonPlayersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public Builder addNonPlayers(
        forfun.sandbox.uwns.shared.pack.proto.Agent.Builder builderForValue) {
      if (nonPlayersBuilder_ == null) {
        ensureNonPlayersIsMutable();
        nonPlayers_.add(builderForValue.build());
        onChanged();
      } else {
        nonPlayersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public Builder addNonPlayers(
        int index, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder builderForValue) {
      if (nonPlayersBuilder_ == null) {
        ensureNonPlayersIsMutable();
        nonPlayers_.add(index, builderForValue.build());
        onChanged();
      } else {
        nonPlayersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public Builder addAllNonPlayers(
        java.lang.Iterable<? extends forfun.sandbox.uwns.shared.pack.proto.Agent> values) {
      if (nonPlayersBuilder_ == null) {
        ensureNonPlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nonPlayers_);
        onChanged();
      } else {
        nonPlayersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public Builder clearNonPlayers() {
      if (nonPlayersBuilder_ == null) {
        nonPlayers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        nonPlayersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public Builder removeNonPlayers(int index) {
      if (nonPlayersBuilder_ == null) {
        ensureNonPlayersIsMutable();
        nonPlayers_.remove(index);
        onChanged();
      } else {
        nonPlayersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Agent.Builder getNonPlayersBuilder(
        int index) {
      return getNonPlayersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder getNonPlayersOrBuilder(
        int index) {
      if (nonPlayersBuilder_ == null) {
        return nonPlayers_.get(index);  } else {
        return nonPlayersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public java.util.List<? extends forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder> 
         getNonPlayersOrBuilderList() {
      if (nonPlayersBuilder_ != null) {
        return nonPlayersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nonPlayers_);
      }
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Agent.Builder addNonPlayersBuilder() {
      return getNonPlayersFieldBuilder().addBuilder(forfun.sandbox.uwns.shared.pack.proto.Agent.getDefaultInstance());
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public forfun.sandbox.uwns.shared.pack.proto.Agent.Builder addNonPlayersBuilder(
        int index) {
      return getNonPlayersFieldBuilder().addBuilder(index, forfun.sandbox.uwns.shared.pack.proto.Agent.getDefaultInstance());
    }
    /**
     * <code>repeated .Agent non_players = 4;</code>
     */
    public java.util.List<forfun.sandbox.uwns.shared.pack.proto.Agent.Builder> 
         getNonPlayersBuilderList() {
      return getNonPlayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        forfun.sandbox.uwns.shared.pack.proto.Agent, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder, forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder> 
        getNonPlayersFieldBuilder() {
      if (nonPlayersBuilder_ == null) {
        nonPlayersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                forfun.sandbox.uwns.shared.pack.proto.Agent, forfun.sandbox.uwns.shared.pack.proto.Agent.Builder, forfun.sandbox.uwns.shared.pack.proto.AgentOrBuilder>(
                nonPlayers_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        nonPlayers_ = null;
      }
      return nonPlayersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SnapshotResponse)
  }

  // @@protoc_insertion_point(class_scope:SnapshotResponse)
  private static final forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse();
  }

  public static forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SnapshotResponse>
      PARSER = new com.google.protobuf.AbstractParser<SnapshotResponse>() {
    public SnapshotResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SnapshotResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SnapshotResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SnapshotResponse> getParserForType() {
    return PARSER;
  }

  public forfun.sandbox.uwns.shared.pack.proto.SnapshotResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

