// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package forfun.sandbox.uwns.shared.pack.proto;

public interface TargetPositionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TargetPositionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Vector position = 1;</code>
   */
  boolean hasPosition();
  /**
   * <code>.Vector position = 1;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.Vector getPosition();
  /**
   * <code>.Vector position = 1;</code>
   */
    forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder getPositionOrBuilder();
}
