// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package forfun.sandbox.uwns.shared.pack.proto;

/**
 * Protobuf type {@code Vector}
 */
public  final class Vector extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Vector)
    VectorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Vector.newBuilder() to construct.
  private Vector(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Vector() {
    x_ = 0F;
    y_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Vector(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 21: {

            x_ = input.readFloat();
            break;
          }
          case 29: {

            y_ = input.readFloat();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Vector_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Vector_fieldAccessorTable
        .ensureFieldAccessorsInitialized(forfun.sandbox.uwns.shared.pack.proto.Vector.class, forfun.sandbox.uwns.shared.pack.proto.Vector.Builder.class);
  }

  public static final int X_FIELD_NUMBER = 2;
  private float x_;
  /**
   * <code>float x = 2;</code>
   */
  public float getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 3;
  private float y_;
  /**
   * <code>float y = 3;</code>
   */
  public float getY() {
    return y_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (x_ != 0F) {
      output.writeFloat(2, x_);
    }
    if (y_ != 0F) {
      output.writeFloat(3, y_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (x_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, x_);
    }
    if (y_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, y_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof forfun.sandbox.uwns.shared.pack.proto.Vector)) {
      return super.equals(obj);
    }
        forfun.sandbox.uwns.shared.pack.proto.Vector other = (forfun.sandbox.uwns.shared.pack.proto.Vector) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getX())
        == java.lang.Float.floatToIntBits(
            other.getX()));
    result = result && (
        java.lang.Float.floatToIntBits(getY())
        == java.lang.Float.floatToIntBits(
            other.getY()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getX());
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getY());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static forfun.sandbox.uwns.shared.pack.proto.Vector parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(forfun.sandbox.uwns.shared.pack.proto.Vector prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Vector}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Vector)
      forfun.sandbox.uwns.shared.pack.proto.VectorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Vector_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Vector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(forfun.sandbox.uwns.shared.pack.proto.Vector.class, forfun.sandbox.uwns.shared.pack.proto.Vector.Builder.class);
    }

    // Construct using forfun.sandbox.uwns.pack.proto.Vector.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      x_ = 0F;

      y_ = 0F;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return forfun.sandbox.uwns.shared.pack.proto.Packet.internal_static_Vector_descriptor;
    }

    public forfun.sandbox.uwns.shared.pack.proto.Vector getDefaultInstanceForType() {
      return forfun.sandbox.uwns.shared.pack.proto.Vector.getDefaultInstance();
    }

    public forfun.sandbox.uwns.shared.pack.proto.Vector build() {
            forfun.sandbox.uwns.shared.pack.proto.Vector result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public forfun.sandbox.uwns.shared.pack.proto.Vector buildPartial() {
            forfun.sandbox.uwns.shared.pack.proto.Vector result = new forfun.sandbox.uwns.shared.pack.proto.Vector(this);
      result.x_ = x_;
      result.y_ = y_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof forfun.sandbox.uwns.shared.pack.proto.Vector) {
        return mergeFrom((forfun.sandbox.uwns.shared.pack.proto.Vector)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(forfun.sandbox.uwns.shared.pack.proto.Vector other) {
      if (other == forfun.sandbox.uwns.shared.pack.proto.Vector.getDefaultInstance()) return this;
      if (other.getX() != 0F) {
        setX(other.getX());
      }
      if (other.getY() != 0F) {
        setY(other.getY());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
            forfun.sandbox.uwns.shared.pack.proto.Vector parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (forfun.sandbox.uwns.shared.pack.proto.Vector) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float x_ ;
    /**
     * <code>float x = 2;</code>
     */
    public float getX() {
      return x_;
    }
    /**
     * <code>float x = 2;</code>
     */
    public Builder setX(float value) {
      
      x_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float x = 2;</code>
     */
    public Builder clearX() {
      
      x_ = 0F;
      onChanged();
      return this;
    }

    private float y_ ;
    /**
     * <code>float y = 3;</code>
     */
    public float getY() {
      return y_;
    }
    /**
     * <code>float y = 3;</code>
     */
    public Builder setY(float value) {
      
      y_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float y = 3;</code>
     */
    public Builder clearY() {
      
      y_ = 0F;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Vector)
  }

  // @@protoc_insertion_point(class_scope:Vector)
  private static final forfun.sandbox.uwns.shared.pack.proto.Vector DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new forfun.sandbox.uwns.shared.pack.proto.Vector();
  }

  public static forfun.sandbox.uwns.shared.pack.proto.Vector getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Vector>
      PARSER = new com.google.protobuf.AbstractParser<Vector>() {
    public Vector parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vector(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Vector> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Vector> getParserForType() {
    return PARSER;
  }

  public forfun.sandbox.uwns.shared.pack.proto.Vector getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

