// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package forfun.sandbox.uwns.shared.pack.proto;

public interface VectorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Vector)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float x = 2;</code>
   */
  float getX();

  /**
   * <code>float y = 3;</code>
   */
  float getY();
}
